<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->partial('renders/_head', array()) ?>
    </head>
    <body>
        <?php echo $this->partial('renders/_header', array()) ?>
        <div class="container">
            <?php echo $this->content; ?>
            <?php echo $this->partial('renders/_footer', array()) ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
