
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php   echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')->setIndent(8) ?>


        <!-- Le styles -->
<?php   echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                  ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                  ->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                  ->appendStylesheet($this->basePath() . '/css/style.css')->setIndent(8) ?>


        <!-- Scripts -->
<?php   $hs = $this->headScript();
        $hs->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
        $hs->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        $hs->appendFile($this->basePath() . '/js/jquery.min.js');
        $hs->appendFile($this->basePath() . '/js/bootstrap.min.js');
        echo $hs->setindent(8); ?>


